-- MySQL Script generated by MySQL Workbench
-- jue 12 jun 2014 10:21:41 CEST
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema aemet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webext` DEFAULT CHARACTER SET latin1 ;
-- -----------------------------------------------------
-- Schema AemetOLD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AemetOLD` ;
USE `webext` ;

-- -----------------------------------------------------
-- Table `webext`.`profesiones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`profesiones` ;

CREATE TABLE IF NOT EXISTS `webext`.`profesiones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `profesion` VARCHAR(45) NOT NULL COMMENT 'Nombre o descripción corta',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `profesion_UNIQUE` (`profesion` ASC))
ENGINE = InnoDB
COMMENT = 'Contiene los tipos de profesiones de cada colaborador.';


-- -----------------------------------------------------
-- Table `webext`.`estudios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`estudios` ;

CREATE TABLE IF NOT EXISTS `webext`.`estudios` (
  `id` TINYINT NOT NULL AUTO_INCREMENT,
  `estudio` VARCHAR(45) NOT NULL COMMENT 'Nombre o descripción corta',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `estudio_UNIQUE` (`estudio` ASC))
ENGINE = InnoDB
COMMENT = 'Contiene los niveles de estudios que puede tener un colaborador:' /* comment truncated */ /*    1 - SIN ESTUDIOS / ESTUDIOS ELEMENTALES
    2 - ESTUDIOS MEDIOS
    3 - ESTUDIOS SUPERIORES*/;


-- -----------------------------------------------------
-- Table `webext`.`colaboradores_tipos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`colaboradores_tipos` ;

CREATE TABLE IF NOT EXISTS `webext`.`colaboradores_tipos` (
  `id` TINYINT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL COMMENT 'Nombre o descripción corta',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tipo_UNIQUE` (`tipo` ASC))
ENGINE = InnoDB
COMMENT = 'Contiene los tipos de colaboradores que existen:' /* comment truncated */ /*    1 - AYUNTAMIENTO
    2 - EMPRESA
    3 - ENTIDAD PUBLICA
    4 - ORDEN RELIGIOSA
    5 - PERSONA FISICA
    6 - ASOCIACION
    7 - CONTACTO*/;


-- -----------------------------------------------------
-- Table `webext`.`delegaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`delegaciones` ;

CREATE TABLE IF NOT EXISTS `webext`.`delegaciones` (
  `cod` CHAR(3) NOT NULL,
  `delegacion` VARCHAR(45) NOT NULL,
  `cif` VARCHAR(9) NOT NULL,
  `delegado_territorial` VARCHAR(45) NOT NULL,
  `presidente_aemet` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod`),
  UNIQUE INDEX `cod_UNIQUE` (`cod` ASC))
ENGINE = InnoDB
COMMENT = 'Contiene la informacion relativa a delegaciones territoriales del AEMET, antes conocidos como CMT (Centros Meteorologicos Territoriales).';


-- -----------------------------------------------------
-- Table `webext`.`colaboradores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`colaboradores` ;

CREATE TABLE IF NOT EXISTS `webext`.`colaboradores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cif_nif` CHAR(9) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `f_alta` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de alta del colaborador',
  `f_modificacion` TIMESTAMP NULL,
  `f_baja` TIMESTAMP NULL COMMENT 'Fecha de baja del colaborador',
  `f_nacimiento` DATE NULL COMMENT 'Fecha de nacimiento',
  `fiabilidad` TINYINT(1) NULL COMMENT 'Fiabilidad como colaborador del 1 al 5.' /* comment truncated */ /*Siendo 5 la mejor.*/,
  `continuidad` TINYINT(1) NULL COMMENT 'Continuidad y frecuencia en el envio de resultados del 1 al 5.' /* comment truncated */ /*Siendo 5 la mejor.*/,
  `profesion_id` INT NULL,
  `estudio_id` TINYINT NULL,
  `colaboradores_tipo_id` TINYINT NULL,
  `colaborador_id` INT NULL,
  `delegacion_cod` CHAR(3) NOT NULL,
  INDEX `fk_colaboradores_profesiones1_idx` (`profesion_id` ASC),
  INDEX `fk_colaboradores_estudios1_idx` (`estudio_id` ASC),
  INDEX `fk_colaboradores_colaboradores_tipos1_idx` (`colaboradores_tipo_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cif_nif_delegacion_cod_UNIQUE` (`cif_nif` ASC, `delegacion_cod` ASC),
  INDEX `fk_colaboradores_delegaciones1_idx` (`delegacion_cod` ASC),
  INDEX `fk_colaboradores_colaboradores1_idx` (`colaborador_id` ASC),
  CONSTRAINT `fk_colaboradores_profesiones1`
    FOREIGN KEY (`profesion_id`)
    REFERENCES `webext`.`profesiones` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_colaboradores_estudios1`
    FOREIGN KEY (`estudio_id`)
    REFERENCES `webext`.`estudios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_colaboradores_colaboradores_tipos1`
    FOREIGN KEY (`colaboradores_tipo_id`)
    REFERENCES `webext`.`colaboradores_tipos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_colaboradores_colaboradores1`
    FOREIGN KEY (`colaborador_id`)
    REFERENCES `webext`.`colaboradores` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_colaboradores_delegaciones1`
    FOREIGN KEY (`delegacion_cod`)
    REFERENCES `webext`.`delegaciones` (`cod`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Contiene los colaboradores de una delegacion y sus datos.' /* comment truncated */ /*Un colaborador puede tener un sustituto que depende de este.
Los datos del sustituto se rellenan en la misma tabla que colaboradores y se diferencian en que incluyen el dni del colaborador del que dependen en el campo "colaboradores_cif_nif"*/;


-- -----------------------------------------------------
-- Table `webext`.`provincias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`provincias` ;

CREATE TABLE IF NOT EXISTS `webext`.`provincias` (
  `cod` CHAR(2) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod`),
  UNIQUE INDEX `provincia_UNIQUE` (`provincia` ASC))
ENGINE = InnoDB
COMMENT = 'Contiene la lista de provincias de España';


-- -----------------------------------------------------
-- Table `webext`.`municipios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`municipios` ;

CREATE TABLE IF NOT EXISTS `webext`.`municipios` (
  `provincia_cod` CHAR(2) NOT NULL,
  `cod` CHAR(3) NOT NULL,
  `municipio` VARCHAR(45) NOT NULL,
  INDEX `fk_municipios_provincias1_idx` (`provincia_cod` ASC),
  PRIMARY KEY (`provincia_cod`, `cod`),
  CONSTRAINT `fk_municipios_provincias1`
    FOREIGN KEY (`provincia_cod`)
    REFERENCES `webext`.`provincias` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Contiene la lista de municipios de España asociados a sus respectivas Provincias';


-- -----------------------------------------------------
-- Table `webext`.`localizadores_tipos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`localizadores_tipos` ;

CREATE TABLE IF NOT EXISTS `webext`.`localizadores_tipos` (
  `id` TINYINT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL COMMENT 'Nombre o descripción corta',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tipo_UNIQUE` (`tipo` ASC))
ENGINE = InnoDB
COMMENT = 'Contiene los tipos de localizadores:' /* comment truncated */ /*1 - Telefono Fijo
2 - Movil
3 - Fax
4 - Email*/;


-- -----------------------------------------------------
-- Table `webext`.`localizadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`localizadores` ;

CREATE TABLE IF NOT EXISTS `webext`.`localizadores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `localizador` VARCHAR(45) NOT NULL COMMENT 'Nombre o descripción corta',
  `principal` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Boolean utilizado para indicar cual es el localizador principal a la hora de ponerse en contacto.',
  `localizadores_tipo_id` TINYINT NOT NULL,
  `colaborador_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_localizadores_localizadores_tipos1_idx` (`localizadores_tipo_id` ASC),
  INDEX `fk_localizadores_colaboradores1_idx` (`colaborador_id` ASC),
  CONSTRAINT `fk_localizadores_localizadores_tipos1`
    FOREIGN KEY (`localizadores_tipo_id`)
    REFERENCES `webext`.`localizadores_tipos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_localizadores_colaboradores1`
    FOREIGN KEY (`colaborador_id`)
    REFERENCES `webext`.`colaboradores` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Asocia un localizador a un colaborador. Un localizador es un medio para ponerse en contacto con un colaborador, como un telefono, un email...' /* comment truncated */ /*Esta ligada a tipos de localizadores y colaboradores.*/;


-- -----------------------------------------------------
-- Table `webext`.`galardones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`galardones` ;

CREATE TABLE IF NOT EXISTS `webext`.`galardones` (
  `id` TINYINT NOT NULL AUTO_INCREMENT,
  `galardon` VARCHAR(45) NOT NULL COMMENT 'Nombre o descripción corta',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `galardon_UNIQUE` (`galardon` ASC))
ENGINE = InnoDB
COMMENT = 'Contiene los tipos de galardones:' /* comment truncated */ /*1 - Diploma
2 - Placa
3 - Premio
4 - Condecoracion*/;


-- -----------------------------------------------------
-- Table `webext`.`cuentas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`cuentas` ;

CREATE TABLE IF NOT EXISTS `webext`.`cuentas` (
  `id` TINYINT NOT NULL AUTO_INCREMENT,
  `ccc` VARCHAR(50) NOT NULL COMMENT 'Cuenta Corriente del Cliente',
  `iban` VARCHAR(45) NULL COMMENT 'International Bank Account Number',
  `colaborador_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cuentas_colaboradores1_idx` (`colaborador_id` ASC),
  CONSTRAINT `fk_cuentas_colaboradores1`
    FOREIGN KEY (`colaborador_id`)
    REFERENCES `webext`.`colaboradores` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Contiene la Cuenta Corriente del Cliente e IBAN de un colaborador.';


-- -----------------------------------------------------
-- Table `webext`.`propietarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`propietarios` ;

CREATE TABLE IF NOT EXISTS `webext`.`propietarios` (
  `id` TINYINT NOT NULL AUTO_INCREMENT,
  `propietario` VARCHAR(45) NOT NULL COMMENT 'Nombre o descripción corta',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `propietario_UNIQUE` (`propietario` ASC))
ENGINE = InnoDB
COMMENT = 'Contiene los tipos de propietarios de una estacion:' /* comment truncated */ /*1 - AJENO AL INM
2 - PROPIO DEL INM*/;


-- -----------------------------------------------------
-- Table `webext`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`categorias` ;

CREATE TABLE IF NOT EXISTS `webext`.`categorias` (
  `id` TINYINT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NOT NULL COMMENT 'Nombre o descripcion corta',
  `observaciones` VARCHAR(500) NULL COMMENT 'Descripcion sobre la categoria que viene relatada en el BOE',
  `limite` DOUBLE NULL COMMENT 'Limite maximo en euros como gratificacion',
  `f_vigor` DATE NULL COMMENT 'Fecha de entrada en vigor de la gratificacion anunciada en el BOE',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`categoria` ASC))
ENGINE = InnoDB
COMMENT = 'Contiene el tipo de categoría de una estación, detalles de esa categoría, límite en EUROS aplicables como gratificacion y fecha de entrada vigor (anunciada en el BOE)';


-- -----------------------------------------------------
-- Table `webext`.`estaciones_tipos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`estaciones_tipos` ;

CREATE TABLE IF NOT EXISTS `webext`.`estaciones_tipos` (
  `id` TINYINT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL COMMENT 'Nombre o descripción corta',
  `observaciones` VARCHAR(45) NULL COMMENT 'Observaciones o informacion extra',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tipo_UNIQUE` (`tipo` ASC))
ENGINE = InnoDB
COMMENT = 'Contiene los tipos de estaciones que hay:' /* comment truncated */ /*0 - OTRO TIPO
1 - AUTOMATICA
2 - PLUVIOMETRICA
3 - TERMOMETRICA
4 - FENOLOGICA */;


-- -----------------------------------------------------
-- Table `webext`.`cuencas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`cuencas` ;

CREATE TABLE IF NOT EXISTS `webext`.`cuencas` (
  `cod` CHAR(2) NOT NULL COMMENT 'El primer digito del indicativo de una estacion indica la cuenca',
  `cuenca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod`))
ENGINE = InnoDB
COMMENT = 'Contiene la lista de cuencas de Españ' /* comment truncated */ /*
0 Pirineo Oriental
1 Norte
2 Duero
3 Tajo
4 Guadiana
5 Guadalquivir
6 Sur
7 Segura
8 Jucar
9 Ebro
10 Baleares
11 Canarias*/;


-- -----------------------------------------------------
-- Table `webext`.`comarcas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`comarcas` ;

CREATE TABLE IF NOT EXISTS `webext`.`comarcas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comarca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Contiene la lista de comarcas de España';


-- -----------------------------------------------------
-- Table `webext`.`islas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`islas` ;

CREATE TABLE IF NOT EXISTS `webext`.`islas` (
  `id` TINYINT NOT NULL AUTO_INCREMENT,
  `isla` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `isla_UNIQUE` (`isla` ASC))
ENGINE = InnoDB
COMMENT = 'Contiene la lista de islas de Españ' /* comment truncated */ /*
0 Cabrera
1 Conejera
2 Formentera
3 Fuerteventura
4 Gran Canaria
5 La Gomera
6 La graciosa
7 Hierro
8 Ibiza
9 Lanzarote
10 Mallorca
11 Menorca
12 La Palma
13 Tenerife*/;


-- -----------------------------------------------------
-- Table `webext`.`estaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`estaciones` ;

CREATE TABLE IF NOT EXISTS `webext`.`estaciones` (
  `indicativo` VARCHAR(10) NOT NULL COMMENT 'El primer caracter indica la cuenca donde se encuentra.' /* comment truncated */ /*Son unicos a nivel nacional.*/,
  `estacion` VARCHAR(45) NOT NULL COMMENT 'Nombre o descripción corta',
  `f_alta` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de alta del colaborador',
  `f_modificacion` TIMESTAMP NULL,
  `f_baja` TIMESTAMP NULL COMMENT 'Fecha de baja del colaborador',
  `propietario_id` TINYINT NOT NULL,
  `categoria_id` TINYINT NOT NULL,
  `estaciones_tipo_id` TINYINT NOT NULL,
  `cuenca_cod` CHAR(2) NOT NULL,
  `comarca_id` INT NULL,
  `isla_id` TINYINT NULL,
  `delegacion_cod` CHAR(3) NOT NULL,
  PRIMARY KEY (`indicativo`),
  INDEX `fk_estaciones_propietarios1_idx` (`propietario_id` ASC),
  INDEX `fk_estaciones_categorias1_idx` (`categoria_id` ASC),
  INDEX `fk_estaciones_estaciones_tipos1_idx` (`estaciones_tipo_id` ASC),
  INDEX `fk_estaciones_cuencas1_idx` (`cuenca_cod` ASC),
  INDEX `fk_estaciones_comarcas1_idx` (`comarca_id` ASC),
  INDEX `fk_estaciones_islas1_idx` (`isla_id` ASC),
  INDEX `fk_estaciones_delegaciones1_idx` (`delegacion_cod` ASC),
  CONSTRAINT `fk_estaciones_propietarios1`
    FOREIGN KEY (`propietario_id`)
    REFERENCES `webext`.`propietarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_estaciones_categorias1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `webext`.`categorias` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_estaciones_estaciones_tipos1`
    FOREIGN KEY (`estaciones_tipo_id`)
    REFERENCES `webext`.`estaciones_tipos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_estaciones_cuencas1`
    FOREIGN KEY (`cuenca_cod`)
    REFERENCES `webext`.`cuencas` (`cod`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_estaciones_comarcas1`
    FOREIGN KEY (`comarca_id`)
    REFERENCES `webext`.`comarcas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_estaciones_islas1`
    FOREIGN KEY (`isla_id`)
    REFERENCES `webext`.`islas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_estaciones_delegaciones1`
    FOREIGN KEY (`delegacion_cod`)
    REFERENCES `webext`.`delegaciones` (`cod`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Contiene las estaciones de una delegacion y sus datos.';


-- -----------------------------------------------------
-- Table `webext`.`direcciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`direcciones` ;

CREATE TABLE IF NOT EXISTS `webext`.`direcciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(45) NULL,
  `cp` VARCHAR(45) NULL,
  `detalles` VARCHAR(45) NULL,
  `principal` TINYINT(1) NOT NULL DEFAULT 0,
  `localidad` VARCHAR(45) NULL,
  `estacion_indicativo` VARCHAR(10) NULL,
  `colaborador_id` INT NULL,
  `delegacion_cod` CHAR(3) NULL,
  `direccionable_id` INT NULL,
  `direccionable_type` VARCHAR(45) NULL,
  `municipios_provincia_cod` CHAR(2) NULL,
  `municipio_cod` CHAR(3) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_direcciones_estaciones1_idx` (`estacion_indicativo` ASC),
  INDEX `fk_direcciones_colaboradores1_idx` (`colaborador_id` ASC),
  INDEX `fk_direcciones_delegaciones1_idx` (`delegacion_cod` ASC),
  INDEX `fk_direcciones_municipios1_idx` (`municipios_provincia_cod` ASC, `municipio_cod` ASC),
  CONSTRAINT `fk_direcciones_estaciones1`
    FOREIGN KEY (`estacion_indicativo`)
    REFERENCES `webext`.`estaciones` (`indicativo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_direcciones_colaboradores1`
    FOREIGN KEY (`colaborador_id`)
    REFERENCES `webext`.`colaboradores` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_direcciones_delegaciones1`
    FOREIGN KEY (`delegacion_cod`)
    REFERENCES `webext`.`delegaciones` (`cod`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_direcciones_municipios1`
    FOREIGN KEY (`municipios_provincia_cod` , `municipio_cod`)
    REFERENCES `webext`.`municipios` (`provincia_cod` , `cod`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Contiene la informacion necesaria para enviar correspondencia y paquetería a un colaborador o una estacion localizada en una direccion fija' /* comment truncated */ /*
Un colaborador o estacion pueden tener diferenctes direcciones almacenadas pero solo una como principal o activa para recibir envíos.*/;


-- -----------------------------------------------------
-- Table `webext`.`colaboradores_has_galardones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`colaboradores_has_galardones` ;

CREATE TABLE IF NOT EXISTS `webext`.`colaboradores_has_galardones` (
  `year` YEAR NOT NULL,
  `galardon_id` TINYINT NOT NULL,
  `colaborador_id` INT NOT NULL,
  PRIMARY KEY (`year`, `galardon_id`, `colaborador_id`),
  INDEX `fk_colaboradores_has_galardones_galardones1_idx` (`galardon_id` ASC),
  INDEX `fk_colaboradores_has_galardones_colaboradores1_idx` (`colaborador_id` ASC),
  CONSTRAINT `fk_colaboradores_has_galardones_galardones1`
    FOREIGN KEY (`galardon_id`)
    REFERENCES `webext`.`galardones` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_colaboradores_has_galardones_colaboradores1`
    FOREIGN KEY (`colaborador_id`)
    REFERENCES `webext`.`colaboradores` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Contiene el tipo de galardon que ha recibido un colaborador y el año de entrega. Esta ligada a colaboradores y tipos de lagardones' /* comment truncated */ /*
Solo se permite entregar un galardon al año.
Un colaborador no puede volver a recibir el mismo tipo de galardon otro año. Se reciben progresivamente y en este orden diploma, placa, premio y condecoracion.*/;


-- -----------------------------------------------------
-- Table `webext`.`eq_propietarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`eq_propietarios` ;

CREATE TABLE IF NOT EXISTS `webext`.`eq_propietarios` (
  `id` INT NOT NULL,
  `propietario` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webext`.`equipos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`equipos` ;

CREATE TABLE IF NOT EXISTS `webext`.`equipos` (
  `id` INT NOT NULL,
  `equipo` VARCHAR(45) NULL,
  `f_instalacion` DATETIME NULL,
  `marca` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `observacion` VARCHAR(45) NULL,
  `eq_propietarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_equipos_propietarios1_idx` (`eq_propietarios_id` ASC),
  CONSTRAINT `fk_equipos_propietarios1`
    FOREIGN KEY (`eq_propietarios_id`)
    REFERENCES `webext`.`eq_propietarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webext`.`eq_mediciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`eq_mediciones` ;

CREATE TABLE IF NOT EXISTS `webext`.`eq_mediciones` (
  `id` INT NOT NULL,
  `medicion` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webext`.`equipos_has_mediciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`equipos_has_mediciones` ;

CREATE TABLE IF NOT EXISTS `webext`.`equipos_has_mediciones` (
  `equipos_id` INT NOT NULL,
  `mediciones_id` INT NOT NULL,
  INDEX `fk_equipos_has_mediciones_mediciones1_idx` (`mediciones_id` ASC),
  INDEX `fk_equipos_has_mediciones_equipos1_idx` (`equipos_id` ASC),
  PRIMARY KEY (`equipos_id`, `mediciones_id`),
  CONSTRAINT `fk_equipos_has_mediciones_equipos1`
    FOREIGN KEY (`equipos_id`)
    REFERENCES `webext`.`equipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipos_has_mediciones_mediciones1`
    FOREIGN KEY (`mediciones_id`)
    REFERENCES `webext`.`eq_mediciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webext`.`eq_caracteristicas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`eq_caracteristicas` ;

CREATE TABLE IF NOT EXISTS `webext`.`eq_caracteristicas` (
  `id` INT NOT NULL,
  `caracteristica` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webext`.`equipos_has_caracteristicas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`equipos_has_caracteristicas` ;

CREATE TABLE IF NOT EXISTS `webext`.`equipos_has_caracteristicas` (
  `equipos_id` INT NOT NULL,
  `caracteristicas_id` INT NOT NULL,
  INDEX `fk_equipos_has_caracteristicas_caracteristicas1_idx` (`caracteristicas_id` ASC),
  INDEX `fk_equipos_has_caracteristicas_equipos1_idx` (`equipos_id` ASC),
  PRIMARY KEY (`caracteristicas_id`, `equipos_id`),
  CONSTRAINT `fk_equipos_has_caracteristicas_equipos1`
    FOREIGN KEY (`equipos_id`)
    REFERENCES `webext`.`equipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipos_has_caracteristicas_caracteristicas1`
    FOREIGN KEY (`caracteristicas_id`)
    REFERENCES `webext`.`eq_caracteristicas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webext`.`fotos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`fotos` ;

CREATE TABLE IF NOT EXISTS `webext`.`fotos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `foto` VARCHAR(45) NOT NULL COMMENT 'Filepath, ruta donde se almacena la foto.',
  `estacion_indicativo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `foto_UNIQUE` (`foto` ASC),
  INDEX `fk_fotos_estaciones1_idx` (`estacion_indicativo` ASC),
  CONSTRAINT `fk_fotos_estaciones1`
    FOREIGN KEY (`estacion_indicativo`)
    REFERENCES `webext`.`estaciones` (`indicativo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Contiene fotos de una estacion.';


-- -----------------------------------------------------
-- Table `webext`.`eq_repuestos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`eq_repuestos` ;

CREATE TABLE IF NOT EXISTS `webext`.`eq_repuestos` (
  `id` INT NOT NULL,
  `repuesto` VARCHAR(45) NULL,
  `cantidad` INT NULL,
  `equipos_id` INT NOT NULL,
  PRIMARY KEY (`id`, `equipos_id`),
  INDEX `fk_repuestos_equipos1_idx` (`equipos_id` ASC),
  CONSTRAINT `fk_repuestos_equipos1`
    FOREIGN KEY (`equipos_id`)
    REFERENCES `webext`.`equipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webext`.`incidencias_tipos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`incidencias_tipos` ;

CREATE TABLE IF NOT EXISTS `webext`.`incidencias_tipos` (
  `id` TINYINT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL COMMENT 'Nombre o descripción corta',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tipo_UNIQUE` (`tipo` ASC))
ENGINE = InnoDB
COMMENT = 'Contiene los tipos de incidencia de una estacion:' /* comment truncated */ /*1 - BAJA DEFINITIVA
2 - CAMBIO DE COLABORADOR
3 - CAMBIO DE EMPLAZAMIENTO
4 - INSTALACIÓN DE MATERIAL
5 - OTRAS
6 - REVISION
7 - CAMBIO DE TIPO DE ESTACION*/;


-- -----------------------------------------------------
-- Table `webext`.`incidencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`incidencias` ;

CREATE TABLE IF NOT EXISTS `webext`.`incidencias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `incidencia` VARCHAR(45) NULL COMMENT 'Nombre o descripción corta',
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de creacion',
  `incidencias_tipo_id` TINYINT NULL,
  `estacion_indicativo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_incidencias_incidencias_tipos1_idx` (`incidencias_tipo_id` ASC),
  INDEX `fk_incidencias_estaciones1_idx` (`estacion_indicativo` ASC),
  CONSTRAINT `fk_incidencias_incidencias_tipos1`
    FOREIGN KEY (`incidencias_tipo_id`)
    REFERENCES `webext`.`incidencias_tipos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_incidencias_estaciones1`
    FOREIGN KEY (`estacion_indicativo`)
    REFERENCES `webext`.`estaciones` (`indicativo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Contiene la incidencia de una estacion y su fecha. Esta ligada a estaciones y tipos de incidencias.';


-- -----------------------------------------------------
-- Table `webext`.`estaciones_has_colaboradores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`estaciones_has_colaboradores` ;

CREATE TABLE IF NOT EXISTS `webext`.`estaciones_has_colaboradores` (
  `estacion_indicativo` VARCHAR(10) NOT NULL,
  `colaborador_id` INT NOT NULL,
  `f_alta` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `f_modificacion` TIMESTAMP NULL,
  `f_baja` TIMESTAMP NULL,
  INDEX `fk_estaciones_has_colaboradores_colaboradores1_idx` (`colaborador_id` ASC),
  INDEX `fk_estaciones_has_colaboradores_estaciones1_idx` (`estacion_indicativo` ASC),
  UNIQUE INDEX `estacion_indicativo_colaborador_id_UNIQUE` (`estacion_indicativo` ASC, `colaborador_id` ASC),
  CONSTRAINT `fk_est_tiene_col_estaciones1`
    FOREIGN KEY (`estacion_indicativo`)
    REFERENCES `webext`.`estaciones` (`indicativo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_est_tiene_col_colaboradores1`
    FOREIGN KEY (`colaborador_id`)
    REFERENCES `webext`.`colaboradores` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Asocia estaciones con colaboradores.' /* comment truncated */ /*Un colaborador puede estar al cargo de varias estaciones y una misma estacion puede ser atendida por varios colaboradores.*/;


-- -----------------------------------------------------
-- Table `webext`.`gratificaciones_estados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`gratificaciones_estados` ;

CREATE TABLE IF NOT EXISTS `webext`.`gratificaciones_estados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL COMMENT 'Nombre o descripción corta',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tipo_UNIQUE` (`estado` ASC))
ENGINE = InnoDB
COMMENT = 'Contiene los tipos de estados de una gratificacion:' /* comment truncated */ /*1 - Anulada
2 - Devuelta
3 - Enviada al Banco
4 - Emitida
5 - Pagada
6 - Propuesta*/;


-- -----------------------------------------------------
-- Table `webext`.`gratificaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`gratificaciones` ;

CREATE TABLE IF NOT EXISTS `webext`.`gratificaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estacion_indicativo` VARCHAR(10) NULL,
  `colaborador_id` INT NOT NULL,
  `year` YEAR NULL,
  `importe` DOUBLE NULL,
  `gratificaciones_estado_id` INT NULL,
  INDEX `fk_gratificaciones_gratificaciones_estados1_idx` (`gratificaciones_estado_id` ASC),
  INDEX `fk_gratificaciones_colaboradores1_idx` (`colaborador_id` ASC),
  INDEX `fk_gratificaciones_estaciones1_idx` (`estacion_indicativo` ASC),
  UNIQUE INDEX `indicativo_col_id_year_UNIQUE` (`estacion_indicativo` ASC, `colaborador_id` ASC, `year` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_gratificaciones_gratificaciones_estados1`
    FOREIGN KEY (`gratificaciones_estado_id`)
    REFERENCES `webext`.`gratificaciones_estados` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_gratificaciones_colaboradores1`
    FOREIGN KEY (`colaborador_id`)
    REFERENCES `webext`.`colaboradores` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_gratificaciones_estaciones1`
    FOREIGN KEY (`estacion_indicativo`)
    REFERENCES `webext`.`estaciones` (`indicativo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Contiene la fecha, importe y tipo de una gratificacion junto con el colaborador beneficiario de esta y la estacion por la cual la recibe. Esta ligada a colaboradores, estaciones y tipo de gratificaciones.';


-- -----------------------------------------------------
-- Table `webext`.`anotaciones_tipos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`anotaciones_tipos` ;

CREATE TABLE IF NOT EXISTS `webext`.`anotaciones_tipos` (
  `id` TINYINT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL COMMENT 'Nombre o descripción corta',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tipo_UNIQUE` (`tipo` ASC))
ENGINE = InnoDB
COMMENT = 'Contiene los tipos de anotaciones que puede tener un colaborador:' /* comment truncated */ /*1 - BAJA POR FALLECIMIENTO
2 - BAJA FORZADA POR EL INSTITUTO
3 - BAJA VOLUNTARIA
4 - Anotacion
5 - Actualizacion*/;


-- -----------------------------------------------------
-- Table `webext`.`anotaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`anotaciones` ;

CREATE TABLE IF NOT EXISTS `webext`.`anotaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `anotacion` VARCHAR(450) NULL COMMENT 'Observaciones o informacion extra',
  `f_alta` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `f_modificacion` TIMESTAMP NULL,
  `f_baja` TIMESTAMP NULL,
  `anotaciones_tipo_id` TINYINT NOT NULL,
  `colaborador_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_anotaciones_anotaciones_tipos1_idx` (`anotaciones_tipo_id` ASC),
  INDEX `fk_anotaciones_colaboradores1_idx` (`colaborador_id` ASC),
  CONSTRAINT `fk_anotaciones_anotaciones_tipos1`
    FOREIGN KEY (`anotaciones_tipo_id`)
    REFERENCES `webext`.`anotaciones_tipos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_anotaciones_colaboradores1`
    FOREIGN KEY (`colaborador_id`)
    REFERENCES `webext`.`colaboradores` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Contiene las anotaciones con su fecha de un colaborador. Esta ligada a colaboradores y tipos de anotaciones.';


-- -----------------------------------------------------
-- Table `webext`.`geolocalizaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`geolocalizaciones` ;

CREATE TABLE IF NOT EXISTS `webext`.`geolocalizaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `f_alta` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de alta',
  `f_modificacion` TIMESTAMP NULL,
  `f_baja` TIMESTAMP NULL COMMENT 'Fecha de baja',
  `longitud_g` TINYINT NULL COMMENT 'De 0 a 180 grados',
  `longitud_m` TINYINT NULL COMMENT 'De 0 a 60 minutos',
  `longitud_s` TINYINT NULL COMMENT 'De 0 a 60 segundos',
  `longitud_w_e` CHAR(1) NULL COMMENT 'West o East',
  `latitud_g` TINYINT NULL COMMENT 'De 0 a 180 grados',
  `latitud_m` TINYINT NULL COMMENT 'De 0 a 60 minutos',
  `latitud_s` TINYINT NULL COMMENT 'De 0 a 60 segundos',
  `latitud_n_s` CHAR(1) NULL COMMENT 'North o South',
  `altitud` INT NULL COMMENT 'Altitud en metros',
  `huso` INT NULL,
  `umt_x` DOUBLE NULL,
  `umt_y` DOUBLE NULL,
  `hoja_mapa` VARCHAR(6) NULL,
  `ubicacion` VARCHAR(45) NULL COMMENT 'En caso de querer acceder fisicamente a la estacion, aqui se facilitara una descripcion de su ubicacion.',
  `estacion_indicativo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_geolocalizaciones_estaciones1_idx` (`estacion_indicativo` ASC),
  CONSTRAINT `fk_geolocalizaciones_estaciones1`
    FOREIGN KEY (`estacion_indicativo`)
    REFERENCES `webext`.`estaciones` (`indicativo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Contiene la informacion necesaria para localizar geograficamente una estacion.' /* comment truncated */ /*Una estacion puede tener varias geolocalizaciones si ha sido transladada en un radio menor a 3KM*/;


-- -----------------------------------------------------
-- Table `webext`.`inspecciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`inspecciones` ;

CREATE TABLE IF NOT EXISTS `webext`.`inspecciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de creacion',
  `observaciones` VARCHAR(45) NULL COMMENT 'Observaciones o informacion extra',
  `estacion_indicativo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_inspecciones_estaciones1_idx` (`estacion_indicativo` ASC),
  CONSTRAINT `fk_inspecciones_estaciones1`
    FOREIGN KEY (`estacion_indicativo`)
    REFERENCES `webext`.`estaciones` (`indicativo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Contiene inspecciones de una estacion y su fecha';


-- -----------------------------------------------------
-- Table `webext`.`credenciales_tipos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`credenciales_tipos` ;

CREATE TABLE IF NOT EXISTS `webext`.`credenciales_tipos` (
  `id` TINYINT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL COMMENT 'Nombre o descripción corta',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Contiene los tipos de usuarios que acceden esta base de datos:' /* comment truncated */ /*1 Administrador
2 Supervisor
3 Lector*/;


-- -----------------------------------------------------
-- Table `webext`.`credenciales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`credenciales` ;

CREATE TABLE IF NOT EXISTS `webext`.`credenciales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(100) NOT NULL,
  `password` CHAR(64) NOT NULL COMMENT 'Hash de la password',
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `puesto` VARCHAR(45) NULL,
  `observaciones` VARCHAR(140) NULL,
  `f_alta` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de alta del colaborador',
  `f_modificacion` TIMESTAMP NULL,
  `f_baja` TIMESTAMP NULL COMMENT 'Fecha de baja del colaborador',
  `credenciales_tipo_id` TINYINT NOT NULL,
  `delegacion_cod` CHAR(3) NULL,
  INDEX `fk_credenciales_credenciales_tipos1_idx` (`credenciales_tipo_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`usuario` ASC),
  INDEX `fk_credenciales_delegaciones2_idx` (`delegacion_cod` ASC),
  CONSTRAINT `fk_credenciales_credenciales_tipos1`
    FOREIGN KEY (`credenciales_tipo_id`)
    REFERENCES `webext`.`credenciales_tipos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_credenciales_delegaciones2`
    FOREIGN KEY (`delegacion_cod`)
    REFERENCES `webext`.`delegaciones` (`cod`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Contiene las credenciales de los usuarios con acceso a la BBDD que dependen de una delegacion.' /* comment truncated */ /*Esta ligada a tipos de usuario y delegaciones*/;


-- -----------------------------------------------------
-- Table `webext`.`credenciales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`credenciales` ;

CREATE TABLE IF NOT EXISTS `webext`.`credenciales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(100) NOT NULL,
  `password` CHAR(64) NOT NULL COMMENT 'Hash de la password',
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `puesto` VARCHAR(45) NULL,
  `observaciones` VARCHAR(140) NULL,
  `f_alta` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de alta del colaborador',
  `f_modificacion` TIMESTAMP NULL,
  `f_baja` TIMESTAMP NULL COMMENT 'Fecha de baja del colaborador',
  `credenciales_tipo_id` TINYINT NOT NULL,
  `delegacion_cod` CHAR(3) NULL,
  INDEX `fk_credenciales_credenciales_tipos1_idx` (`credenciales_tipo_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`usuario` ASC),
  INDEX `fk_credenciales_delegaciones2_idx` (`delegacion_cod` ASC),
  CONSTRAINT `fk_credenciales_credenciales_tipos1`
    FOREIGN KEY (`credenciales_tipo_id`)
    REFERENCES `webext`.`credenciales_tipos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_credenciales_delegaciones2`
    FOREIGN KEY (`delegacion_cod`)
    REFERENCES `webext`.`delegaciones` (`cod`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Contiene las credenciales de los usuarios con acceso a la BBDD que dependen de una delegacion.' /* comment truncated */ /*Esta ligada a tipos de usuario y delegaciones*/;


-- -----------------------------------------------------
-- Table `webext`.`xc_colaborador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webext`.`xc_colaborador` ;

CREATE TABLE IF NOT EXISTS `webext`.`xc_colaborador` (
  `s_Generation` INT(11) NULL DEFAULT NULL,
  `s_GUID` VARCHAR(38) NULL DEFAULT NULL,
  `s_Lineage` LONGBLOB NULL DEFAULT NULL,
  `CMT_CODIGOID` VARCHAR(2) NOT NULL,
  `CIF_NIF` VARCHAR(9) NOT NULL,
  `TIPO` VARCHAR(2) NULL DEFAULT NULL,
  `NOMBRE` VARCHAR(50) NULL DEFAULT NULL,
  `APELLIDOS` VARCHAR(50) NOT NULL,
  `DIRECCION` VARCHAR(50) NULL DEFAULT NULL,
  `LOCALIDAD` VARCHAR(50) NULL DEFAULT NULL,
  `ISLA` VARCHAR(30) NULL DEFAULT NULL,
  `PROV_CODIGOID` VARCHAR(2) NOT NULL,
  `MUNI_CODIGOID` VARCHAR(3) NOT NULL,
  `CODIPOST` VARCHAR(5) NOT NULL,
  `TELEFONO` VARCHAR(9) NULL DEFAULT NULL,
  `TELEFONO2` VARCHAR(9) NULL DEFAULT NULL,
  `FAX` VARCHAR(9) NULL DEFAULT NULL,
  `EMAIL` VARCHAR(50) NULL DEFAULT NULL,
  `ENTIDAD` VARCHAR(4) NULL DEFAULT NULL,
  `AGENCIA` VARCHAR(4) NULL DEFAULT NULL,
  `CUENTA_BAN` VARCHAR(10) NULL DEFAULT NULL,
  `DC` VARCHAR(2) NULL DEFAULT NULL,
  `F_NACIMIENTO` DATETIME NULL DEFAULT NULL,
  `TIPO_PROFESION` VARCHAR(1) NULL DEFAULT NULL,
  `PROFESION` VARCHAR(30) NULL DEFAULT NULL,
  `ESTUDIOS` VARCHAR(1) NULL DEFAULT NULL,
  `F_DIPLOMA` VARCHAR(4) NULL DEFAULT NULL,
  `F_PLACA` VARCHAR(4) NULL DEFAULT NULL,
  `F_PREMIO` VARCHAR(4) NULL DEFAULT NULL,
  `F_CONDECORACION` VARCHAR(4) NULL DEFAULT NULL,
  `SELECCION` TINYINT(1) NULL DEFAULT '0',
  `ACTIVO` TINYINT(1) NULL DEFAULT '0',
  `FOTO` VARCHAR(100) NULL DEFAULT NULL,
  `USUARIO` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`CMT_CODIGOID`, `CIF_NIF`),
  UNIQUE INDEX `s_GUID` (`s_GUID` ASC),
  INDEX `s_Generation` (`s_Generation` ASC),
  INDEX `PROV_CODIGOID` (`PROV_CODIGOID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

USE `AemetOLD` ;

-- -----------------------------------------------------
-- Table `AemetOLD`.`municipios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AemetOLD`.`municipios` ;

CREATE TABLE IF NOT EXISTS `AemetOLD`.`municipios` (
  `id_municipio` SMALLINT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_provincia` SMALLINT(6) NOT NULL,
  `cod_municipio` INT(11) NOT NULL COMMENT 'Código de muncipio DENTRO de la provincia, campo no único',
  `DC` INT(11) NOT NULL COMMENT 'Digito Control. El INE no revela cómo se calcula, secreto nuclear.',
  `nombre` VARCHAR(100) NOT NULL DEFAULT '',
  PRIMARY KEY (`id_municipio`))
ENGINE = InnoDB
AUTO_INCREMENT = 8117
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `AemetOLD`.`ref_codes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AemetOLD`.`ref_codes` ;

CREATE TABLE IF NOT EXISTS `AemetOLD`.`ref_codes` (
  `CODIGO` VARCHAR(10) NOT NULL,
  `s_Generation` INT(11) NULL DEFAULT NULL,
  `s_GUID` VARCHAR(38) NULL DEFAULT NULL,
  `s_Lineage` LONGBLOB NULL DEFAULT NULL,
  `DOMINIO` VARCHAR(20) NOT NULL,
  `SIGNIFICADO` VARCHAR(50) NOT NULL,
  `COMENTARIO` VARCHAR(100) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `AemetOLD`.`x1_cab_gratificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AemetOLD`.`x1_cab_gratificacion` ;

CREATE TABLE IF NOT EXISTS `AemetOLD`.`x1_cab_gratificacion` (
  `Gen_OBSERVA` INT(11) NULL DEFAULT NULL,
  `s_Generation` INT(11) NULL DEFAULT NULL,
  `s_GUID` VARCHAR(38) NULL DEFAULT NULL,
  `s_Lineage` LONGBLOB NULL DEFAULT NULL,
  `CMT_CODIGOID` VARCHAR(2) NOT NULL,
  `ANYO` INT(11) NOT NULL DEFAULT '0',
  `CODIGOID` INT(11) NOT NULL DEFAULT '0',
  `EST_COL_CODIGOID` INT(11) NOT NULL DEFAULT '0',
  `EST_CODIGOID` VARCHAR(5) NOT NULL,
  `COL_CIF_NIF` VARCHAR(9) NOT NULL,
  `ESTADO` VARCHAR(2) NOT NULL,
  `FECHA_INICIO` DATETIME NULL DEFAULT NULL,
  `FECHA_FIN` DATETIME NULL DEFAULT NULL,
  `F_EMISION` DATETIME NULL DEFAULT NULL,
  `F_SOLICITUD` DATETIME NULL DEFAULT NULL,
  `F_ENVIO_BAN` DATETIME NULL DEFAULT NULL,
  `F_DEVOLUCION` DATETIME NULL DEFAULT NULL,
  `F_ANULACION` DATETIME NULL DEFAULT NULL,
  `BANCO_CODIGOID` VARCHAR(4) NULL DEFAULT NULL,
  `AGENURBA` VARCHAR(4) NULL DEFAULT NULL,
  `NUMECUEN` VARCHAR(10) NULL DEFAULT NULL,
  `DIGICONT` VARCHAR(2) NULL DEFAULT NULL,
  `IMPORTE` DOUBLE NULL DEFAULT '0',
  `DIVISA` VARCHAR(3) NOT NULL,
  `SELECCION` TINYINT(1) NULL DEFAULT '0',
  `OBSERVA` LONGTEXT NULL DEFAULT NULL,
  `USUARIO` VARCHAR(50) NULL DEFAULT NULL)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `AemetOLD`.`x1_concepto_gratificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AemetOLD`.`x1_concepto_gratificacion` ;

CREATE TABLE IF NOT EXISTS `AemetOLD`.`x1_concepto_gratificacion` (
  `s_Generation` INT(11) NULL DEFAULT NULL,
  `s_GUID` VARCHAR(38) NULL DEFAULT NULL,
  `s_Lineage` LONGBLOB NULL DEFAULT NULL,
  `CMT_CODIGOID` VARCHAR(2) NOT NULL,
  `EST_COL_CODIGOID` INT(11) NOT NULL DEFAULT '0',
  `CODIGOID` INT(11) NOT NULL DEFAULT '0',
  `FECHA_VIGOR` DATETIME NOT NULL,
  `CONCEPTO_CODIGOID` VARCHAR(3) NULL DEFAULT NULL,
  `CONCEPTO` VARCHAR(100) NOT NULL,
  `IMPORTE` DOUBLE NOT NULL DEFAULT '0',
  `DIVISA` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`CMT_CODIGOID`, `EST_COL_CODIGOID`, `CODIGOID`),
  UNIQUE INDEX `s_GUID` (`s_GUID` ASC),
  INDEX `s_Generation` (`s_Generation` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `AemetOLD`.`x1_estacion_colaborador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AemetOLD`.`x1_estacion_colaborador` ;

CREATE TABLE IF NOT EXISTS `AemetOLD`.`x1_estacion_colaborador` (
  `Gen_OBSERVA` INT(11) NULL DEFAULT NULL,
  `s_Generation` INT(11) NULL DEFAULT NULL,
  `s_GUID` VARCHAR(38) NULL DEFAULT NULL,
  `s_Lineage` LONGBLOB NULL DEFAULT NULL,
  `CMT_CODIGOID` VARCHAR(2) NOT NULL,
  `CODIGOID` INT(11) NOT NULL DEFAULT '0',
  `EST_CODIGOID` VARCHAR(5) NOT NULL,
  `COL_CIF_NIF` VARCHAR(9) NOT NULL,
  `FIABILIDAD` VARCHAR(1) NULL DEFAULT NULL,
  `CONTINUIDAD` VARCHAR(1) NULL DEFAULT NULL,
  `FECHA_ALTA` DATETIME NOT NULL,
  `FECHA_BAJA` DATETIME NULL DEFAULT NULL,
  `GENERAR_GRAT` TINYINT(1) NOT NULL DEFAULT '0',
  `FECULLIQ` DATETIME NULL DEFAULT NULL,
  `IMPORTE` DOUBLE NOT NULL DEFAULT '0',
  `DIVISA` VARCHAR(3) NOT NULL,
  `SELECCION` TINYINT(1) NULL DEFAULT '0',
  `OBSERLIQ` VARCHAR(100) NULL DEFAULT NULL,
  `OBSERVA` LONGTEXT NULL DEFAULT NULL,
  `USUARIO` VARCHAR(50) NULL DEFAULT NULL)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `AemetOLD`.`x1_linea_gratificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AemetOLD`.`x1_linea_gratificacion` ;

CREATE TABLE IF NOT EXISTS `AemetOLD`.`x1_linea_gratificacion` (
  `s_Generation` INT(11) NULL DEFAULT NULL,
  `s_GUID` VARCHAR(38) NULL DEFAULT NULL,
  `s_Lineage` LONGBLOB NULL DEFAULT NULL,
  `CMT_CODIGOID` VARCHAR(2) NOT NULL,
  `ANYO` INT(11) NOT NULL DEFAULT '0',
  `GRAT_CODIGOID` INT(11) NOT NULL DEFAULT '0',
  `CODIGOID` INT(11) NOT NULL DEFAULT '0',
  `CONCEPTO_CODIGOID` VARCHAR(3) NULL DEFAULT NULL,
  `CONCEPTO` VARCHAR(100) NOT NULL,
  `IMPORTE` DOUBLE NOT NULL DEFAULT '0',
  `DIVISA` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`CMT_CODIGOID`, `ANYO`, `GRAT_CODIGOID`, `CODIGOID`),
  UNIQUE INDEX `s_GUID` (`s_GUID` ASC),
  INDEX `s_Generation` (`s_Generation` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `AemetOLD`.`x1_tipo_gratificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AemetOLD`.`x1_tipo_gratificacion` ;

CREATE TABLE IF NOT EXISTS `AemetOLD`.`x1_tipo_gratificacion` (
  `s_Generation` INT(11) NULL DEFAULT NULL,
  `s_GUID` VARCHAR(38) NULL DEFAULT NULL,
  `s_Lineage` LONGBLOB NULL DEFAULT NULL,
  `FECHA_VIGOR` DATETIME NOT NULL,
  `CMT_CODIGOID` VARCHAR(2) NOT NULL,
  `CODIGOID` VARCHAR(3) NOT NULL,
  `CONCEPTO` VARCHAR(100) NOT NULL,
  `IMPORTE` DOUBLE NOT NULL DEFAULT '0',
  `DIVISA` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`FECHA_VIGOR`, `CMT_CODIGOID`, `CODIGOID`),
  UNIQUE INDEX `s_GUID` (`s_GUID` ASC),
  INDEX `s_Generation` (`s_Generation` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `AemetOLD`.`xc_colaborador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AemetOLD`.`xc_colaborador` ;

CREATE TABLE IF NOT EXISTS `AemetOLD`.`xc_colaborador` (
  `s_Generation` INT(11) NULL DEFAULT NULL,
  `s_GUID` VARCHAR(38) NULL DEFAULT NULL,
  `s_Lineage` LONGBLOB NULL DEFAULT NULL,
  `CMT_CODIGOID` VARCHAR(2) NOT NULL,
  `CIF_NIF` VARCHAR(9) NOT NULL,
  `TIPO` VARCHAR(2) NULL DEFAULT NULL,
  `NOMBRE` VARCHAR(50) NULL DEFAULT NULL,
  `APELLIDOS` VARCHAR(50) NOT NULL,
  `DIRECCION` VARCHAR(50) NULL DEFAULT NULL,
  `LOCALIDAD` VARCHAR(50) NULL DEFAULT NULL,
  `ISLA` VARCHAR(30) NULL DEFAULT NULL,
  `PROV_CODIGOID` VARCHAR(2) NOT NULL,
  `MUNI_CODIGOID` VARCHAR(3) NOT NULL,
  `CODIPOST` VARCHAR(5) NOT NULL,
  `TELEFONO` VARCHAR(9) NULL DEFAULT NULL,
  `TELEFONO2` VARCHAR(9) NULL DEFAULT NULL,
  `FAX` VARCHAR(9) NULL DEFAULT NULL,
  `EMAIL` VARCHAR(50) NULL DEFAULT NULL,
  `ENTIDAD` VARCHAR(4) NULL DEFAULT NULL,
  `AGENCIA` VARCHAR(4) NULL DEFAULT NULL,
  `CUENTA_BAN` VARCHAR(10) NULL DEFAULT NULL,
  `DC` VARCHAR(2) NULL DEFAULT NULL,
  `F_NACIMIENTO` DATETIME NULL DEFAULT NULL,
  `TIPO_PROFESION` VARCHAR(1) NULL DEFAULT NULL,
  `PROFESION` VARCHAR(30) NULL DEFAULT NULL,
  `ESTUDIOS` VARCHAR(1) NULL DEFAULT NULL,
  `F_DIPLOMA` VARCHAR(4) NULL DEFAULT NULL,
  `F_PLACA` VARCHAR(4) NULL DEFAULT NULL,
  `F_PREMIO` VARCHAR(4) NULL DEFAULT NULL,
  `F_CONDECORACION` VARCHAR(4) NULL DEFAULT NULL,
  `SELECCION` TINYINT(1) NULL DEFAULT '0',
  `ACTIVO` TINYINT(1) NULL DEFAULT '0',
  `FOTO` VARCHAR(100) NULL DEFAULT NULL,
  `USUARIO` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`CMT_CODIGOID`, `CIF_NIF`),
  UNIQUE INDEX `s_GUID` (`s_GUID` ASC),
  INDEX `s_Generation` (`s_Generation` ASC),
  INDEX `PROV_CODIGOID` (`PROV_CODIGOID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `AemetOLD`.`xc_col_asociados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AemetOLD`.`xc_col_asociados` ;

CREATE TABLE IF NOT EXISTS `AemetOLD`.`xc_col_asociados` (
  `Gen_OBSERVACIONES` INT(11) NULL DEFAULT NULL,
  `s_Generation` INT(11) NULL DEFAULT NULL,
  `s_GUID` VARCHAR(38) NULL DEFAULT NULL,
  `s_Lineage` LONGBLOB NULL DEFAULT NULL,
  `CMT_CODIGOID` VARCHAR(2) NOT NULL,
  `COL_CIF_NIF` VARCHAR(9) NOT NULL,
  `CODIGOID` INT(11) NOT NULL DEFAULT '0',
  `NOMBRE` VARCHAR(50) NOT NULL,
  `RELACION` VARCHAR(25) NULL DEFAULT NULL,
  `F_ALTA` DATETIME NULL DEFAULT NULL,
  `F_BAJA` DATETIME NULL DEFAULT NULL,
  `DIRECCION` VARCHAR(50) NULL DEFAULT NULL,
  `TELEFONO` VARCHAR(9) NULL DEFAULT NULL,
  `OBSERVACIONES` LONGTEXT NULL DEFAULT NULL)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `AemetOLD`.`xc_col_incidencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AemetOLD`.`xc_col_incidencia` ;

CREATE TABLE IF NOT EXISTS `AemetOLD`.`xc_col_incidencia` (
  `Gen_INCIDENCIA` INT(11) NULL DEFAULT NULL,
  `s_Generation` INT(11) NULL DEFAULT NULL,
  `s_GUID` VARCHAR(38) NULL DEFAULT NULL,
  `s_Lineage` LONGBLOB NULL DEFAULT NULL,
  `CMT_CODIGOID` VARCHAR(2) NOT NULL,
  `COL_CIF_NIF` VARCHAR(9) NOT NULL,
  `CODIGOID` INT(11) NOT NULL DEFAULT '0',
  `FECHAINC` DATETIME NOT NULL,
  `TIPOINC` VARCHAR(3) NOT NULL,
  `INCIDENCIA` LONGTEXT NOT NULL)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `AemetOLD`.`xg_agencia_ban`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AemetOLD`.`xg_agencia_ban` ;

CREATE TABLE IF NOT EXISTS `AemetOLD`.`xg_agencia_ban` (
  `ENTIDAD` VARCHAR(4) NOT NULL,
  `s_Generation` INT(11) NULL DEFAULT NULL,
  `s_GUID` VARCHAR(38) NULL DEFAULT NULL,
  `s_Lineage` LONGBLOB NULL DEFAULT NULL,
  `AGENCIA` VARCHAR(4) NOT NULL,
  `DIRECCION` VARCHAR(50) NULL DEFAULT NULL,
  `PROV_CODIGOID` VARCHAR(2) NULL DEFAULT NULL,
  `MUNI_CODIGOID` VARCHAR(3) NULL DEFAULT NULL,
  PRIMARY KEY (`ENTIDAD`, `AGENCIA`),
  UNIQUE INDEX `s_GUID` (`s_GUID` ASC),
  INDEX `s_Generation` (`s_Generation` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `AemetOLD`.`xg_banco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AemetOLD`.`xg_banco` ;

CREATE TABLE IF NOT EXISTS `AemetOLD`.`xg_banco` (
  `ENTIDAD` VARCHAR(4) NOT NULL,
  `s_Generation` INT(11) NULL DEFAULT NULL,
  `s_GUID` VARCHAR(38) NULL DEFAULT NULL,
  `s_Lineage` LONGBLOB NULL DEFAULT NULL,
  `NOMBRE` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`ENTIDAD`),
  UNIQUE INDEX `ENTIDAD` (`ENTIDAD` ASC),
  UNIQUE INDEX `s_GUID` (`s_GUID` ASC),
  INDEX `s_Generation` (`s_Generation` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `AemetOLD`.`xg_globales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AemetOLD`.`xg_globales` ;

CREATE TABLE IF NOT EXISTS `AemetOLD`.`xg_globales` (
  `CMT_CODIGOID` VARCHAR(2) NOT NULL,
  `DESCRIPCION` VARCHAR(50) NOT NULL,
  `CIF` VARCHAR(9) NOT NULL,
  `DIRECCION` VARCHAR(50) NOT NULL,
  `COD_POSTAL` VARCHAR(5) NOT NULL,
  `PROV_CODIGOID` VARCHAR(2) NOT NULL,
  `MUNI_CODIGOID` VARCHAR(3) NOT NULL,
  `DIRECTOR` VARCHAR(45) NOT NULL,
  `DIRECTOR_INM` VARCHAR(45) NOT NULL,
  `ENTIDAD` VARCHAR(4) NOT NULL,
  `AGENCIA` VARCHAR(4) NOT NULL,
  `DC` VARCHAR(2) NOT NULL,
  `CUENTA_BAN` VARCHAR(10) NOT NULL,
  `CMT_CSB` VARCHAR(10) NOT NULL,
  `CODIGO_PRESENTADOR` VARCHAR(5) NULL DEFAULT NULL,
  `HABILITADO` VARCHAR(30) NULL DEFAULT NULL,
  `TEL_HABILITADO` INT(11) NULL DEFAULT '0',
  `TIPO_TRANSFERENCIA` VARCHAR(2) NULL DEFAULT NULL,
  `FACTOR_CONVERSION` DOUBLE NULL DEFAULT '0',
  `NUM_SECRETO_1` VARCHAR(12) NULL DEFAULT NULL,
  `NUM_SECRETO_2` VARCHAR(12) NULL DEFAULT NULL,
  `NUM_SECRETO_3` VARCHAR(12) NULL DEFAULT NULL,
  `NUM_SECRETO_4` VARCHAR(12) NULL DEFAULT NULL,
  `NUM_SECRETO_5` VARCHAR(12) NULL DEFAULT NULL,
  `NUM_SECRETO_6` VARCHAR(12) NULL DEFAULT NULL,
  `NUM_SECRETO_7` VARCHAR(12) NULL DEFAULT NULL,
  `NUM_SECRETO_8` VARCHAR(12) NULL DEFAULT NULL,
  `NUM_SECRETO_9` VARCHAR(12) NULL DEFAULT NULL,
  `NUM_SECRETO_10` VARCHAR(12) NULL DEFAULT NULL,
  `NUM_SECRETO_11` VARCHAR(12) NULL DEFAULT NULL,
  `NUM_SECRETO_12` VARCHAR(12) NULL DEFAULT NULL,
  `NUM_SECRETO_13` VARCHAR(12) NULL DEFAULT NULL,
  `NUM_SECRETO_14` VARCHAR(12) NULL DEFAULT NULL,
  `NUM_SECRETO_15` VARCHAR(12) NULL DEFAULT NULL,
  `NUM_SECRETO_16` VARCHAR(12) NULL DEFAULT NULL,
  `NUM_SECRETO_17` VARCHAR(12) NULL DEFAULT NULL,
  `NUM_SECRETO_18` VARCHAR(12) NULL DEFAULT NULL,
  `NUM_SECRETO_19` VARCHAR(12) NULL DEFAULT NULL,
  `NUM_SECRETO_20` VARCHAR(12) NULL DEFAULT NULL,
  PRIMARY KEY (`CMT_CODIGOID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `AemetOLD`.`xg_municipio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AemetOLD`.`xg_municipio` ;

CREATE TABLE IF NOT EXISTS `AemetOLD`.`xg_municipio` (
  `provincias_cod` CHAR(2) NOT NULL,
  `cod` CHAR(3) NOT NULL,
  `municipio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`provincias_cod`, `cod`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `AemetOLD`.`xg_provincia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AemetOLD`.`xg_provincia` ;

CREATE TABLE IF NOT EXISTS `AemetOLD`.`xg_provincia` (
  `id` TINYINT(2) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `AemetOLD`.`xs_equipamiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AemetOLD`.`xs_equipamiento` ;

CREATE TABLE IF NOT EXISTS `AemetOLD`.`xs_equipamiento` (
  `Gen_OBSERVACIO` INT(11) NULL DEFAULT NULL,
  `s_Generation` INT(11) NULL DEFAULT NULL,
  `s_GUID` VARCHAR(38) NULL DEFAULT NULL,
  `s_Lineage` LONGBLOB NULL DEFAULT NULL,
  `COD_EQUI` DOUBLE NOT NULL,
  `NOMB_EQUI` VARCHAR(255) NOT NULL,
  `MARCA` VARCHAR(20) NULL DEFAULT NULL,
  `MODELO` VARCHAR(10) NULL DEFAULT NULL,
  `REPUESTOS` VARCHAR(50) NULL DEFAULT NULL,
  `OBSERVACIO` LONGTEXT NULL DEFAULT NULL)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `AemetOLD`.`xs_estacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AemetOLD`.`xs_estacion` ;

CREATE TABLE IF NOT EXISTS `AemetOLD`.`xs_estacion` (
  `s_Generation` INT(11) NULL DEFAULT NULL,
  `s_GUID` VARCHAR(38) NULL DEFAULT NULL,
  `s_Lineage` LONGBLOB NULL DEFAULT NULL,
  `CMT_CODIGOID` VARCHAR(2) NOT NULL,
  `CODIGOID` VARCHAR(5) NOT NULL,
  `NOMBRE` VARCHAR(50) NOT NULL,
  `CUENCA` VARCHAR(20) NULL DEFAULT NULL,
  `COMARCA` VARCHAR(20) NULL DEFAULT NULL,
  `TIPO1_ID` VARCHAR(1) NOT NULL,
  `TIPO2_ID` VARCHAR(1) NULL DEFAULT NULL,
  `TIPO3_ID` VARCHAR(1) NULL DEFAULT NULL,
  `TIPO4_ID` VARCHAR(1) NULL DEFAULT NULL,
  `TIPO5_ID` VARCHAR(1) NULL DEFAULT NULL,
  `OTRO_TIPO` VARCHAR(20) NULL DEFAULT NULL,
  `ESTADO_ID` VARCHAR(1) NOT NULL,
  `CATEGORIA_ID` VARCHAR(2) NOT NULL,
  `F_ALTA` DATETIME NULL DEFAULT NULL,
  `F_ULT_INSPEC` DATETIME NULL DEFAULT NULL,
  `F_BAJA` DATETIME NULL DEFAULT NULL,
  `LOCALIDAD` VARCHAR(50) NULL DEFAULT NULL,
  `ISLA` VARCHAR(50) NULL DEFAULT NULL,
  `PROV_CODIGOID` VARCHAR(2) NOT NULL,
  `MUNI_CODIGOID` VARCHAR(3) NOT NULL,
  `LONGITUD_GR` INT(11) NULL DEFAULT '0',
  `LONGITUD_MI` INT(11) NULL DEFAULT '0',
  `LONGITUD_SG` FLOAT NULL DEFAULT '0',
  `LONGITUD_W_E` VARCHAR(1) NULL DEFAULT 'W',
  `LATITUD_GR` INT(11) NULL DEFAULT '0',
  `LATITUD_MI` INT(11) NULL DEFAULT '0',
  `LATITUD_SG` FLOAT NULL DEFAULT '0',
  `LATITUD_N_S` VARCHAR(1) NULL DEFAULT 'N',
  `ALTITUD` INT(11) NULL DEFAULT NULL,
  `HUSO` INT(11) NULL DEFAULT NULL,
  `X_UTM` DOUBLE NULL DEFAULT NULL,
  `Y_UTM` DOUBLE NULL DEFAULT NULL,
  `HOJA_MAPA` VARCHAR(6) NULL DEFAULT NULL,
  `UBICACION` VARCHAR(50) NULL DEFAULT NULL,
  `USUARIO` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`CMT_CODIGOID`, `CODIGOID`),
  UNIQUE INDEX `s_GUID` (`s_GUID` ASC),
  INDEX `s_Generation` (`s_Generation` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `AemetOLD`.`xs_estacion_foto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AemetOLD`.`xs_estacion_foto` ;

CREATE TABLE IF NOT EXISTS `AemetOLD`.`xs_estacion_foto` (
  `s_Generation` INT(11) NULL DEFAULT NULL,
  `s_GUID` VARCHAR(38) NULL DEFAULT NULL,
  `s_Lineage` LONGBLOB NULL DEFAULT NULL,
  `CMT_CODIGOID` VARCHAR(2) NOT NULL,
  `EST_CODIGOID` VARCHAR(5) NOT NULL,
  `FECHAINC` DATETIME NOT NULL,
  `FOTO` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`CMT_CODIGOID`, `EST_CODIGOID`, `FECHAINC`),
  UNIQUE INDEX `s_GUID` (`s_GUID` ASC),
  INDEX `s_Generation` (`s_Generation` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `AemetOLD`.`xs_estacion_incidencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AemetOLD`.`xs_estacion_incidencia` ;

CREATE TABLE IF NOT EXISTS `AemetOLD`.`xs_estacion_incidencia` (
  `Gen_INCIDENCIA` INT(11) NULL DEFAULT NULL,
  `s_Generation` INT(11) NULL DEFAULT NULL,
  `s_GUID` VARCHAR(38) NULL DEFAULT NULL,
  `s_Lineage` LONGBLOB NULL DEFAULT NULL,
  `CMT_CODIGOID` VARCHAR(2) NOT NULL,
  `EST_CODIGOID` VARCHAR(5) NOT NULL,
  `CODIGOID` INT(11) NOT NULL DEFAULT '0',
  `FECHAINC` DATETIME NOT NULL,
  `TIPOINC` VARCHAR(3) NOT NULL,
  `INCIDENCIA` LONGTEXT NOT NULL)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `AemetOLD`.`xs_estac_equipa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AemetOLD`.`xs_estac_equipa` ;

CREATE TABLE IF NOT EXISTS `AemetOLD`.`xs_estac_equipa` (
  `CMT_CODIGOID` VARCHAR(2) NOT NULL,
  `Gen_OBSERVACION` INT(11) NULL DEFAULT NULL,
  `s_Generation` INT(11) NULL DEFAULT NULL,
  `s_GUID` VARCHAR(38) NULL DEFAULT NULL,
  `s_Lineage` LONGBLOB NULL DEFAULT NULL,
  `EST_CODIGOID` VARCHAR(5) NOT NULL,
  `COD_EQUI` DOUBLE NOT NULL,
  `PROPIEDAD` VARCHAR(1) NULL DEFAULT NULL,
  `PROPIETARIO` VARCHAR(30) NULL DEFAULT NULL,
  `F_ALTA` DATETIME NULL DEFAULT NULL,
  `OBSERVACION` LONGTEXT NULL DEFAULT NULL)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
